/*
Deployment script for AutomatedTESTS_PodcastsManager

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "AutomatedTESTS_PodcastsManager"
:setvar DefaultFilePrefix "AutomatedTESTS_PodcastsManager"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Check Constraint [dbo].[CK_PodcastGuests_Rating]...';


GO
ALTER TABLE [dbo].[PodcastGuests] DROP CONSTRAINT [CK_PodcastGuests_Rating];


GO
PRINT N'Unbinding columns from changing objects on table [dbo].[InterviewRequests]...';


GO
ALTER TABLE [dbo].[InterviewRequests] ALTER COLUMN [LastName] VARCHAR (150) NOT NULL;


GO
PRINT N'Dropping User-Defined Data Type [dbo].[LastName]...';


GO
DROP TYPE [dbo].[LastName];


GO
PRINT N'Creating User-Defined Data Type [dbo].[LastName]...';


GO
CREATE TYPE [dbo].[LastName]
    FROM VARCHAR (160) NOT NULL;


GO
PRINT N'Rebinding columns to changed objects on table [dbo].[InterviewRequests]...';


GO
ALTER TABLE [dbo].[InterviewRequests] ALTER COLUMN [LastName] [dbo].[LastName] NOT NULL;


GO
PRINT N'Creating Check Constraint [dbo].[CK_PodcastGuests_Rating]...';


GO
ALTER TABLE [dbo].[PodcastGuests] WITH NOCHECK
    ADD CONSTRAINT [CK_PodcastGuests_Rating] CHECK ([ChefRating] between 0 and 5);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[PodcastGuests] WITH CHECK CHECK CONSTRAINT [CK_PodcastGuests_Rating];


GO
PRINT N'Update complete.';


GO
